# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45fbcd6c72d3dcbe9ca30d83721c485e05bd83fafdfe8e3f2f877806eafa5e12a6dbb0dcafe0da13bc27a1921e8b3d4da50590fa7813d82a16516b6694630066

test:
  secret_key_base: a605039becc69f32d6b5fc456566ec2f51df6bb23733be6d79279fb1c2246fa222a44686d917717922b2680106b5749bb23f7919a3a60277fb1b7d9ba68fed4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
